Document: gtkrsync
Title: Debian gtkrsync Manual
Author: <insert document author here>
Abstract: This manual describes what gtkrsync is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gtkrsync/gtkrsync.sgml.gz

Format: postscript
Files: /usr/share/doc/gtkrsync/gtkrsync.ps.gz

Format: text
Files: /usr/share/doc/gtkrsync/gtkrsync.text.gz

Format: HTML
Index: /usr/share/doc/gtkrsync/html/index.html
Files: /usr/share/doc/gtkrsync/html/*.html

  
